#!/bin/bash

set -euo pipefail

PULL_FROM="${PWD%/.git}"

cd "/opt/linac-scripts"

unset GIT_DIR

echo "[$PWD] git remote set-url origin \"$PULL_FROM\"" >&2

git remote add origin "$PULL_FROM" 2>/dev/null ||
    git remote set-url origin "$PULL_FROM"

echo "[$PWD] git reset --hard origin/master" >&2

git fetch --force origin &&
    git reset --hard origin/master

echo "[$PWD] Done." >&2
