#!/bin/bash
# shellcheck disable=SC2034

#CLOUDIMG_POOL_ROOT="/var/lib/libvirt/images"
#CLOUDIMG_SESSION_POOL_ROOT="$HOME/.local/share/libvirt/images"
#UBUNTU_CLOUDIMG_HOST="cloud-images.ubuntu.com"
#UBUNTU_APT_MIRROR="http://archive.ubuntu.com/ubuntu"

SCREENSHOT_DIR="$HOME/Pictures/Screenshots"

NOTE_DIR="$HOME/Documents/Notes"

SAMBA_WORKGROUP="WORKGROUP"

GIT_URL_REPLACEMENTS=(
    's/https:\/\/github\.com\//github.com:/'
    's/ssh:\/\/([^/]+)\//\1:/'
)

DEFAULT_CODE_ROOTS=("$LK_ROOT")
[ -z "${HOME:-}" ] || DEFAULT_CODE_ROOTS+=("$HOME/Code")
