#!/bin/bash
# shellcheck disable=SC2034

#SCREENSHOT_DIR="$HOME/Pictures/Screenshots"

#SAMBA_WORKGROUP="LINAC"

DEFAULT_CODE_ROOTS=()
if [ -n "${HOME:-}" ]; then
    DEFAULT_CODE_ROOTS+=("$HOME/Code")
    [[ "$ROOT_DIR" == "$HOME/Code"* ]] || DEFAULT_CODE_ROOTS+=("$ROOT_DIR")
else
    DEFAULT_CODE_ROOTS+=("$ROOT_DIR")
fi
