#!/bin/bash
# shellcheck disable=SC2034

#CLOUDIMG_POOL_ROOT="/var/lib/libvirt/images"
#UBUNTU_CLOUDIMG_HOST="cloud-images.ubuntu.com"

SCREENSHOT_DIR="$HOME/Pictures/Screenshots"

SCRATCHPAD_DIR="$HOME/Documents/Notes/Daily"

SAMBA_WORKGROUP="WORKGROUP"

GIT_URL_REPLACEMENTS=(
    's/https:\/\/github\.com\//github.com:/'
    's/ssh:\/\/([^/]+)\//\1:/'
)

DEFAULT_CODE_ROOTS=("$LK_ROOT")
[ -z "${HOME:-}" ] || DEFAULT_CODE_ROOTS+=("$HOME/Code")
