#!/bin/bash
# shellcheck disable=SC1090
# Reviewed: 2019-10-25

function service_get_property() {

    local SERVICE_NAME PROPERTY_NAME PROPS PROP VAL

    SERVICE_NAME="$1"
    PROPERTY_NAME="$2"
    shift 2

    [ -n "$SERVICE_NAME" ] || die
    [ -n "$PROPERTY_NAME" ] || die

    PROPS="$(systemctl "$@" show --property="$PROPERTY_NAME" "$SERVICE_NAME.service")" || die
    IFS="=" read -r PROP VAL <<<"$PROPS" || true
    [ "$PROP" = "$PROPERTY_NAME" ] || die

    echo "$VAL"

}

function service_property_is() {

    local SERVICE_NAME PROPERTY_NAME EXPECTED_VALUE VALUE

    SERVICE_NAME="$1"
    PROPERTY_NAME="$2"
    EXPECTED_VALUE="$3"
    shift 3

    VALUE="$(
        . "$SUBSHELL_SCRIPT_PATH" || exit
        service_get_property "$SERVICE_NAME" "$PROPERTY_NAME" "$@"
    )" || die

    [ "$VALUE" = "$EXPECTED_VALUE" ]

}

function service_exists() {

    local SERVICE_NAME

    SERVICE_NAME="$1"
    shift

    ! service_property_is "$SERVICE_NAME" "LoadState" "not-found" "$@"

}

function system_service_exists() {

    service_exists "$1"

}

function user_service_exists() {

    service_exists "$1" --user

}

function system_service_running() {

    systemctl --quiet is-active "$1.service"

}

function user_service_running() {

    systemctl --user --quiet is-active "$1.service"

}

function freedesktop_disable_autostart() {

    if [ ! -e "$HOME/.config/autostart/$1.desktop" ]; then

        cat <<EOF >"$HOME/.config/autostart/$1.desktop"
[Desktop Entry]
Hidden=true

EOF

    fi

}

# Reviewed: 2019-11-05
function disable_update_motd() {

    local FILE DISABLE=(10-help-text 50-motd-news 80-esm 80-livepatch 90-updates-available 91-release-upgrade 95-hwe-eol)

    [ "$#" -eq "0" ] || DISABLE=("$@")

    [ "${#DISABLE[@]}" -eq "0" ] || console_message "Disabling update-motd.d entries:" "${DISABLE[*]}" "$CYAN"

    for FILE in "${DISABLE[@]}"; do

        if [ -x "/etc/update-motd.d/$FILE" ]; then

            maybe_dryrun sudo chmod -v a-x "/etc/update-motd.d/$FILE"

        fi

    done

}
