#!/bin/bash
# shellcheck disable=SC2034,SC2206,SC2207

if ! command_exists brew; then

    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" || die

fi

function brew_check_taps() {

    local MISSING_TAPS TAP

    MISSING_TAPS=($(comm -23 <(printf '%s\n' "${BREW_TAPS[@]}" | sort | uniq) <(brew tap | sort | uniq)))

    if [ "${#MISSING_TAPS[@]}" -gt "0" ]; then

        console_message "Adding ${#MISSING_TAPS[@]} Homebrew $(single_or_plural "${#MISSING_TAPS[@]}" tap taps):" "${MISSING_TAPS[*]}" "$GREEN"

        for TAP in "${MISSING_TAPS[@]}"; do

            brew tap "$TAP" || die

        done

        [ "$BREW_CACHE_DIRTY" -ne "0" ] || brew_refresh

    fi

}

function brew_refresh() {

    BREW_INSTALLED_FORMULAE="$(brew list | sort | uniq)" || die
    BREW_AVAILABLE_FORMULAE="$(brew search | sort | uniq)" || die
    BREW_INSTALLED_CASKS="$(brew cask list | sort | uniq)" || die
    BREW_AVAILABLE_CASKS="$(brew search --casks | sort | uniq)" || die

}

function brew_formula_installed() {

    brew_make_cache_clean
    echo "$BREW_INSTALLED_FORMULAE" | grep -E '^'"$1"'$' >/dev/null 2>&1

}

function brew_formula_just_installed() {

    if [ "${#BREW_JUST_INSTALLED[@]}" -gt "0" ]; then

        printf '%s\n' "${BREW_JUST_INSTALLED[@]}" | grep -E '^'"$1"'$' >/dev/null 2>&1

    else

        false

    fi

}

function brew_formula_installed_or_queued() {

    if ! brew_formula_installed "$1"; then

        if [ "${#BREW_FORMULA_QUEUE[@]}" -gt "0" ]; then

            printf '%s\n' "${BREW_FORMULA_QUEUE[@]}" | grep -E '^'"$1"'$' >/dev/null 2>&1

        else

            false

        fi

    else

        true

    fi

}

function brew_formula_available() {

    brew_make_cache_clean
    echo "$BREW_AVAILABLE_FORMULAE" | grep -E '^'"$1"'$' >/dev/null 2>&1

}

function brew_mark_cache_clean() {

    [ "$BREW_CACHE_DIRTY" -ne "0" ] && brew_refresh && BREW_CACHE_DIRTY=0

}

function brew_make_cache_clean() {

    if [ "$BREW_CACHE_DIRTY" -ne "0" ]; then

        console_message "Updating lists..." "" "$CYAN"

        brew update && brew_refresh && BREW_CACHE_DIRTY=0 || die

    fi

}

# Usage: brew_queue_formulae "Description of this group of formulae" "formula1 formula2 ..." [allow user override? (Y/n)]
function brew_queue_formulae() {

    brew_make_cache_clean

    install_or_queue "$1" "$2" "${3:-Y}" formula formulae BREW_INSTALLED_FORMULAE BREW_AVAILABLE_FORMULAE BREW_FORMULA_QUEUE BREW_INSTALLED

}

# Usage: brew_queue_casks "Description of this group of casks" "cask1 cask2 ..." [allow user override? (Y/n)]
function brew_queue_casks() {

    brew_make_cache_clean

    install_or_queue "$1" "$2" "${3:-Y}" cask casks BREW_INSTALLED_CASKS BREW_AVAILABLE_CASKS BREW_CASK_QUEUE BREW_INSTALLED

}

function brew_process_queue() {

    if [ "${#BREW_FORMULA_QUEUE[@]}" -gt "0" ]; then

        console_message "Installing ${#BREW_FORMULA_QUEUE[@]} $(single_or_plural "${#BREW_FORMULA_QUEUE[@]}" formula formulae):" "${BREW_FORMULA_QUEUE[*]}" "$GREEN"

        brew install "${BREW_FORMULA_QUEUE[@]}" && {
            BREW_INSTALLED+=("${BREW_FORMULA_QUEUE[@]}")
            BREW_JUST_INSTALLED+=("${BREW_FORMULA_QUEUE[@]}")
        } || die

    fi

    if [ "${#BREW_CASK_QUEUE[@]}" -gt "0" ]; then

        console_message "Installing ${#BREW_CASK_QUEUE[@]} $(single_or_plural "${#BREW_CASK_QUEUE[@]}" cask casks):" "${BREW_CASK_QUEUE[*]}" "$GREEN"

        brew cask install --no-quarantine --force "${BREW_CASK_QUEUE[@]}" && {
            BREW_INSTALLED+=("${BREW_CASK_QUEUE[@]}")
            BREW_JUST_INSTALLED+=("${BREW_CASK_QUEUE[@]}")
        } || die

    fi

    BREW_FORMULA_QUEUE=()
    BREW_CASK_QUEUE=()
    brew_refresh

}

BREW_TAPS=(
    homebrew/cask-drivers
    homebrew/cask-fonts
    homebrew/cask-versions
)

BREW_CACHE_DIRTY=1
BREW_FORMULA_QUEUE=()
BREW_CASK_QUEUE=()
BREW_INSTALLED=()
BREW_JUST_INSTALLED=()
