#!/bin/bash
# shellcheck disable=

function check_developer_tools() {

    local ATTEMPTS=0

    assert_command_exists xcode-select

    while ! xcode-select -p >/dev/null; do

        [ "$ATTEMPTS" -eq "0" ] || console_message "Command line developer tools aren't installed ($ATTEMPTS $(single_or_plural "$ATTEMPTS" attempt attempts) so far)" "" "$BOLD" "$RED"

        console_message "Requesting installation of the command line developer tools" "" "$GREEN"
        sudo xcode-select --install

        get_enter "Press Enter when command line developer tools installation has completed"

        ((++ATTEMPTS))

    done

}
