#!/bin/bash
# shellcheck disable=SC2034

set -euo pipefail

function error_trap() {

    echo "Error: $(basename "$0") failed with exit code $1 in $2 at line $3" >&2
    exit "$1"

}

trap 'error_trap "$?" "${BASH_SOURCE[0]}" "$LINENO"' ERR

set -E

function exit_trap() {

    local i

    for i in "${!DELETE_ON_EXIT[@]}"; do

        rm -Rf "${DELETE_ON_EXIT[$i]}" || true

    done

    for i in "${!KILL_ON_EXIT[@]}"; do

        kill "${KILL_ON_EXIT[$i]}" || true

    done

}

trap exit_trap EXIT

ORIGINAL_BASH_SUBSHELL="$BASH_SUBSHELL"

DELETE_ON_EXIT=()
KILL_ON_EXIT=()
