#!/bin/bash

assert_is_linux

if ! command_exists apt-get || ! command_exists dpkg; then

    die "Error: $(basename "$0") requires apt and dpkg"

fi

function apt_require_package() {

    if get_confirmation "$(basename "$0") needs to install the $1 package. Is that OK?" Y Y; then

        sudo apt-get install -y "$1" || die

    else

        die

    fi

}

function apt_refresh_packages() {

    APT_INSTALLED_PACKAGES="$(dpkg-query -f '${binary:Package}\n' -W | sort | uniq)" || die
    APT_AVAILABLE_PACKAGES="$(apt-cache pkgnames | sort | uniq)" || die

    if [ "$APT_GUI_PACKAGES_AUTO" -eq "1" ] || ! variable_exists APT_GUI_PACKAGES; then

        APT_GUI_PACKAGES="$(
            # shellcheck source=../bash/common-subshell
            . "$SUBSHELL_SCRIPT_PATH" || exit
            apt-cache rdepends --recurse --no-recommends --no-suggests --no-conflicts --no-breaks --no-replaces --no-enhances libwayland-client0 libwayland-server0 libx11-6 x11-common | grep -v " " | sort | uniq
        )" || die
        APT_GUI_PACKAGES_AUTO=1

    fi

}

function apt_package_installed() {

    apt_make_cache_clean
    echo "$APT_INSTALLED_PACKAGES" | grep -E "^$1"'(:.*)?$' >/dev/null 2>&1

}

function apt_package_just_installed() {

    printf '%s\n' "${APT_JUST_INSTALLED[@]}" | grep -E "^$1"'(:.*)?$' >/dev/null 2>&1

}

function apt_package_available() {

    apt_make_cache_clean
    echo "$APT_AVAILABLE_PACKAGES" | grep -E "^$1"'(:.*)?$' >/dev/null 2>&1

}

function apt_package_is_gui() {

    apt_make_cache_clean
    apt_package_available "$1" && echo "$APT_GUI_PACKAGES" | grep -E "^$1"'(:.*)?$' >/dev/null 2>&1

}

function apt_package_is_cli() {

    apt_package_available "$1" && ! apt_package_is_gui "$1"

}

# Removes duplicates and suppressed packages.
# Usage: apt_filter_packages "package1 package2 package3-" [include removed? (Y/n)]
function apt_filter_packages() {

    local PACKAGES=($1) INCLUDE_REMOVED="${2:-Y}" FILTERED=() p

    PACKAGES=($(printf '%s\n' "${PACKAGES[@]}" | sort | uniq))

    for p in "${PACKAGES[@]}"; do

        if [ "${p:(-1)}" = "-" ]; then

            # don't ever include suppressions
            apt_package_installed "${p::(-1)}" || continue

            # optionally include removals
            [ "$INCLUDE_REMOVED" = "Y" ] || continue

        fi

        FILTERED+=("$p")

    done

    echo "${FILTERED[*]}"

}

# Underlines "gui" packages, and colours packages being removed red. Optionally reflows text.
# Usage: apt_pretty_packages "package1 package2 package3-" [reflow text? (y/N)] ["$BLUE" ...]
function apt_pretty_packages() {

    local PACKAGES=($1) FORMATTED="$1" REFLOW="${2:-N}" REFLOWED=() COLOUR_RESET="${RESET}" p q s r

    [ "$#" -gt "2" ] && {
        shift
        shift
        COLOUR_RESET="$(printf '%s' "$@")"
    } || true

    for p in "${PACKAGES[@]}"; do

        s="$(sed_escape_search "$p")"
        q="$p"

        if [ "${p:(-1)}" = "-" ]; then

            p="${p::(-1)}"
            q="${BOLD}${RED}${p} "

        fi

        apt_package_is_gui "$p" && q="${UNDERLINE}${q}${NO_UNDERLINE}"
        q="${q}${COLOUR_RESET}"

        r="$(sed_escape_replace "$q")"

        if [ "$REFLOW" = "N" ]; then

            FORMATTED="$(echo "$FORMATTED" | sed -E 's/(\s|^)'"$s"'(\s|$)/\1'"$r"'\2/g')"

        else

            # remove trailing space
            REFLOWED+=("${q% }")

        fi

    done

    if [ "$REFLOW" = "N" ]; then

        echo "$FORMATTED"

    else

        echo "${REFLOWED[*]}"

    fi

}

function apt_ubuntu_archive_url() {

    # attempt to identify a local archive URL
    if [ -z "${UBUNTU_ARCHIVE_URL:-}" ]; then

        UBUNTU_ARCHIVE_URL="$(
            set -euo pipefail
            grep -Eo '\bhttps?://([[:alnum:]]+\.)archive\.ubuntu\.com/ubuntu\b' /etc/apt/sources.list | head -n1
        )/" || UBUNTU_ARCHIVE_URL="http://archive.ubuntu.com/ubuntu/"

    fi

    echo "$UBUNTU_ARCHIVE_URL"

}

function do_apt_enable_ubuntu_repository() {

    if ! grep -E '^deb[[:space:]]+https?://([[:alnum:]]+\.)?archive\.ubuntu\.com/ubuntu/?[[:space:]]+'"$1"'[[:space:]]+.*\b'"$2"'\b' </etc/apt/sources.list >/dev/null 2>&1; then

        command_exists add-apt-repository || apt_force_install_packages "software-properties-common"

        sudo add-apt-repository -yn "deb $(apt_ubuntu_archive_url) $1 $2" || die

        APT_CACHE_DIRTY=1

    fi

}

function apt_enable_ubuntu_repository() {

    assert_is_ubuntu

    do_apt_enable_ubuntu_repository "$DISTRIB_CODENAME" "$1"

    local suffix

    [ -n "${2:-}" ] && for suffix in $2; do

        do_apt_enable_ubuntu_repository "${DISTRIB_CODENAME}-${suffix}" "$1"

    done

}

function apt_enable_partner_repository() {

    assert_is_ubuntu

    if ! grep -E '^deb[[:space:]]+https?://([[:alnum:]]+\.)?archive\.canonical\.com/ubuntu/?[[:space:]]+'"$DISTRIB_CODENAME"'[[:space:]]+.*\bpartner\b' </etc/apt/sources.list >/dev/null 2>&1; then

        command_exists add-apt-repository || apt_force_install_packages "software-properties-common"

        sudo add-apt-repository -yn "deb http://archive.canonical.com/ubuntu $DISTRIB_CODENAME partner" || die

        APT_CACHE_DIRTY=1

    fi

}

# Usage: apt_register_ppa "the/ppa" "package1 package2 ..." [add immediately? (y/N)] [allow only named packages? (Y/n)]
function apt_register_ppa() {

    command_exists add-apt-repository || apt_force_install_packages "software-properties-common"

    local p PREFERENCES=

    if [ -n "$2" ]; then

        if [ "${4:-Y}" = "Y" ]; then

            # exits non-zero on EOF
            IFS= read -rd '' PREFERENCES <<EOF || true
Package: *
Pin: release o=LP-PPA-${1/\//-}
Pin-Priority: 400

Package: $2
Pin: release o=LP-PPA-${1/\//-}
Pin-Priority: 500
EOF

        fi

    fi

    if ! cat /etc/apt/sources.list /etc/apt/sources.list.d/*.list 2>/dev/null | grep "^[^#]*/$1" >/dev/null 2>&1; then

        for p in $2; do

            # without BASH 4+, we have to kludge our associative arrays
            APT_PPA_REGISTRY+=("$1")
            APT_PPA_PACKAGES+=("$p")
            APT_PPA_PREFERENCES+=("$PREFERENCES")

        done

        if [ "${3:-N}" = "Y" ]; then

            apt_add_ppa "$1"

        fi

    elif [ -n "$PREFERENCES" ]; then

        echo "$PREFERENCES" | sudo tee "/etc/apt/preferences.d/ppa-${1//[\/.]/-}.pref" >/dev/null || die

    fi

}

function apt_add_key_from_url() {

    wget -qO - "$1" | sudo apt-key add - >/dev/null 2>&1 || die "Error: unable to add GPG key from $1"

}

# Usage: apt_register_repository my-repo-identifier "https://gpg.key.url" "content for my-repo-identifier.list" "value for Pin field in apt preferences" "package1 package2 ..." [add immediately? (y/N)] [allow only named packages? (Y/n)]
function apt_register_repository() {

    command_exists wget || apt_force_install_packages "wget"

    local p PREFERENCES=

    if [ -n "$4" ] && [ -n "$5" ]; then

        if [ "${7:-Y}" = "Y" ]; then

            # exits non-zero on EOF
            IFS= read -rd '' PREFERENCES <<EOF || true
Package: *
Pin: $4
Pin-Priority: 400

Package: $5
Pin: $4
Pin-Priority: 500
EOF

        fi

    fi

    if [ ! -e "/etc/apt/sources.list.d/$1.list" ]; then

        for p in $5; do

            # without BASH 4+, we have to kludge our associative arrays
            APT_REPO_REGISTRY+=("$1")
            APT_REPO_KEY_URLS+=("$2")
            APT_REPO_ENTRIES+=("$3")
            APT_REPO_PACKAGES+=("$p")
            APT_REPO_PREFERENCES+=("$PREFERENCES")

        done

        if [ "${6:-N}" = "Y" ]; then

            apt_add_repo "$1"

        fi

    else

        # because keys change sometimes
        apt_add_key_from_url "$2"

        if [ -n "$PREFERENCES" ]; then

            echo "$PREFERENCES" | sudo tee "/etc/apt/preferences.d/$1.pref" >/dev/null || die

        fi

    fi

}

# use this when you don't need the latest package index files
function apt_mark_cache_clean() {

    [ "$APT_CACHE_DIRTY" -ne "0" ] && apt_refresh_packages && APT_CACHE_DIRTY=0

}

function apt_make_cache_clean() {

    if [ "$APT_CACHE_DIRTY" -ne "0" ]; then

        console_message "Updating package lists..." "" "$CYAN"

        sudo apt-get "${APT_GET_OPTIONS[@]}" -qq update && apt_refresh_packages && APT_CACHE_DIRTY=0 || die

    fi

}

# Usage: apt_get_package_list "${INSTALL[*]}" "${IGNORED[*]}" "${SUPPRESSED[*]}" "${REMOVE[*]}" "${SILENCED[*]}" [return silent? (Y/N)]
function apt_get_package_list() {

    local p q IGNORED=" $2 " SUPPRESSED=($3) REMOVE=($4) SILENCED=" $5 " RETURN_SILENT="${6:-N}" LIST=() BAD_LIST=()

    for p in $1; do

        # suppressed? lift the suppression
        for q in "${!SUPPRESSED[@]}"; do

            [ "$p" = "${SUPPRESSED[$q]}" ] && unset "SUPPRESSED[$q]" || true

        done

        # being removed? not anymore
        for q in "${!REMOVE[@]}"; do

            [ "$p" = "${REMOVE[$q]}" ] && unset "REMOVE[$q]" || true

        done

        # return silent and non-silent packages separately
        if [[ "$SILENCED" == *" $p "* ]]; then

            [ "$RETURN_SILENT" = "Y" ] || continue

        else

            [ "$RETURN_SILENT" != "Y" ] || continue

        fi

        # unavailable? ignore if possible, otherwise add to BAD_LIST
        if ! apt_package_available "$p"; then

            if [[ "$IGNORED" == *" $p "* ]]; then

                APT_SKIPPED+=("$p")

            else

                BAD_LIST+=("$p")

            fi

            continue

        fi

        LIST+=("$p")

    done

    [ "${#BAD_LIST[@]}" -gt "0" ] && console_message "$(single_or_plural ${#BAD_LIST[@]} Package Packages) unavailable for installation:" "${BAD_LIST[*]}" "$BOLD" "$RED" >&2 && die

    for q in "${REMOVE[@]}"; do

        apt_package_installed "$q" && LIST+=("${q}-")

    done

    [ "${#LIST[@]}" -gt "0" ] && for q in "${SUPPRESSED[@]}"; do

        # suppressing doesn't mean removing
        ! apt_package_installed "$q" && LIST+=("${q}-")

    done

    echo "${LIST[*]}"

}

# Usage: apt_install_packages "Description of this group of packages" "package1 package2 ..." [allow user override (Y/N)] [queue only (Y/N)]
function apt_install_packages() {

    local UI="${3:-Y}" QUEUE_ONLY="${4:-Y}" INSTALLED=() INSTALL=() IGNORED=() SUPPRESSED=() SILENCED=() IGNORE SUPPRESS SILENCE PPA_QUEUE=() PPA_INDEX REPO_QUEUE=() REPO_INDEX OPTIONS QUEUE PROMPT_EXTRA="" INSTALL_QUEUE SILENT_QUEUE PRETTY_QUEUE SUDO_EXTRA=() p q

    apt_make_cache_clean

    console_message "Checking $1..." "" "$CYAN"

    for p in $2; do

        IGNORE=0
        SUPPRESS=0
        SILENCE=0

        while [[ "${p:(-1)}" =~ [+?\!-] ]]; do

            case "${p:(-1)}" in

            "?")
                IGNORE=1
                ;;

            "-")
                SUPPRESS=1
                ;;

            "!")
                SILENCE=1
                ;;

            esac

            p="${p::(-1)}"

        done

        [ "$SUPPRESS" -eq "1" ] && SUPPRESSED+=("$p") && continue || true
        [ "$IGNORE" -eq "1" ] && IGNORED+=("$p") || true
        [ "$SILENCE" -eq "1" ] && SILENCED+=("$p") || true

        PPA_INDEX=$(array_search "$p" APT_PPA_PACKAGES) || true
        REPO_INDEX=$(array_search "$p" APT_REPO_PACKAGES) || true

        if [ -n "$PPA_INDEX" ]; then

            INSTALL+=("$p")
            PPA_QUEUE+=("${APT_PPA_REGISTRY[$PPA_INDEX]}")

        elif [ -n "$REPO_INDEX" ]; then

            INSTALL+=("$p")
            REPO_QUEUE+=("${APT_REPO_REGISTRY[$REPO_INDEX]}")

        elif apt_package_installed "$p"; then

            INSTALLED+=("$p")

        else

            # if this package is allowed to be unavailable, isn't associated with a queued repo, and isn't available, ignore it now rather than prompting the user
            if [ "$IGNORE" -eq "1" ] && [ -z "$PPA_INDEX" ] && [ -z "$REPO_INDEX" ] && ! apt_package_available "$p"; then

                APT_SKIPPED+=("$p")

            else

                INSTALL+=("$p")

            fi

        fi

    done

    APT_INSTALLED+=("${INSTALLED[@]}")

    if [ "${#INSTALL[@]}" -gt "0" ]; then

        OPTIONS=("${APT_GET_OPTIONS[@]}")

        QUEUE=($(printf '%s\n' "${PPA_QUEUE[@]}" "${REPO_QUEUE[@]}" | sort | uniq))

        if [ "$UI" = "Y" ]; then

            console_message "Missing $1 $(single_or_plural ${#INSTALL[@]} package packages):" "$(apt_pretty_packages "$(apt_filter_packages "${INSTALL[*]}")" Y "$BOLD" "$MAGENTA")" "$BOLD" "$MAGENTA"

            [ "${#QUEUE[@]}" -gt "0" ] && {
                console_message "These packages depend on ${#QUEUE[@]} missing $(single_or_plural ${#QUEUE[@]} repository repositories):" "${QUEUE[*]}" "$BOLD" "$MAGENTA"
                PROMPT_EXTRA=" and $(single_or_plural ${#QUEUE[@]} repository repositories)"
            }

            get_confirmation "Add the $1 $(single_or_plural ${#INSTALL[@]} package packages)${PROMPT_EXTRA} listed above?" Y Y || return 0

        else

            [[ "${APT_GET_OPTIONS[*]}" =~ ([[:space:]]|^)(-y|--yes|--assume-yes)([[:space:]]|$) ]] || OPTIONS+=("-y")

        fi

        if [ "$QUEUE_ONLY" = "N" ]; then

            [ "${#QUEUE[@]}" -gt "0" ] && console_message "Adding ${#QUEUE[@]} $(single_or_plural ${#QUEUE[@]} repository repositories):" "${QUEUE[*]}" "$GREEN"

            for q in PPA REPO; do

                eval QUEUE='("${'$q'_QUEUE[@]}")'

                [ "${#QUEUE[@]}" -gt "0" ] && {
                    QUEUE=($(printf '%s\n' "${QUEUE[@]}" | sort | uniq))
                    eval "apt_add_$(lower $q)" "${QUEUE[@]}" || die
                }

            done

            apt_make_cache_clean
            INSTALL_QUEUE=($(apt_get_package_list "${INSTALL[*]}" "${IGNORED[*]}" "${SUPPRESSED[*]}" "" "${SILENCED[*]}" N))
            SILENT_QUEUE=($(apt_get_package_list "${INSTALL[*]}" "${IGNORED[*]}" "${SUPPRESSED[*]}" "" "${SILENCED[*]}" Y))
            PRETTY_QUEUE=($(apt_pretty_packages "$(apt_filter_packages "${INSTALL_QUEUE[*]} ${SILENT_QUEUE[*]}")" Y "$GREEN"))
            console_message "Installing ${#PRETTY_QUEUE[@]} $(single_or_plural ${#PRETTY_QUEUE[@]} package packages):" "${PRETTY_QUEUE[*]}" "$GREEN"

            for q in INSTALL SILENT; do

                eval QUEUE='("${'$q'_QUEUE[@]}")'

                if [ "${#QUEUE[@]}" -gt "0" ]; then

                    sudo "${SUDO_EXTRA[@]}" apt-get "${OPTIONS[@]}" install "${QUEUE[@]}" && {
                        APT_INSTALLED+=($(apt_filter_packages "${QUEUE[*]}" N))
                        APT_JUST_INSTALLED+=($(apt_filter_packages "${QUEUE[*]}" N))
                    } || die

                fi

                SUDO_EXTRA+=("DEBIAN_FRONTEND=noninteractive")

            done

            apt_refresh_packages

        else

            APT_INSTALL_QUEUE+=("${INSTALL[@]}")
            APT_IGNORED+=("${IGNORED[@]}")
            APT_SUPPRESSED+=("${SUPPRESSED[@]}")
            APT_SILENCED+=("${SILENCED[@]}")
            APT_PPA_QUEUE+=("${PPA_QUEUE[@]}")
            APT_REPO_QUEUE+=("${REPO_QUEUE[@]}")

        fi

    fi

}

function apt_add_ppa() {

    local ppa i PREFERENCES

    for ppa in $(printf '%s\n' "$@" | sort | uniq); do

        [ -z "$ppa" ] && continue || true

        i=$(array_search "$ppa" APT_PPA_REGISTRY) || die "Error: unable to find metadata for PPA '$ppa'"

        sudo add-apt-repository -yn "ppa:$ppa" || die

        PREFERENCES="${APT_PPA_PREFERENCES[$i]}"

        if [ -n "$PREFERENCES" ]; then

            echo "$PREFERENCES" | sudo tee "/etc/apt/preferences.d/ppa-${ppa//[\/.]/-}.pref" >/dev/null || die

        fi

        APT_CACHE_DIRTY=1

        for i in "${!APT_PPA_REGISTRY[@]}"; do

            if [ "$ppa" = "${APT_PPA_REGISTRY[$i]}" ]; then

                unset "APT_PPA_REGISTRY[$i]"
                unset "APT_PPA_PACKAGES[$i]"
                unset "APT_PPA_PREFERENCES[$i]"

            fi

        done

        for i in "${!APT_PPA_QUEUE[@]}"; do

            if [ "$ppa" = "${APT_PPA_QUEUE[$i]}" ]; then

                unset "APT_PPA_QUEUE[$i]"

            fi

        done

    done

}

function apt_add_repo() {

    local repo i KEY_URL ENTRY

    for repo in $(printf '%s\n' "$@" | sort | uniq); do

        [ -z "$repo" ] && continue || true

        i=$(array_search "$repo" APT_REPO_REGISTRY) || die "Error: unable to find metadata for repository '$repo'"

        KEY_URL="${APT_REPO_KEY_URLS[$i]}"
        ENTRY="${APT_REPO_ENTRIES[$i]}"
        PREFERENCES="${APT_REPO_PREFERENCES[$i]}"

        echo "$ENTRY" | sudo tee "/etc/apt/sources.list.d/$repo.list" >/dev/null || die

        apt_add_key_from_url "$KEY_URL"

        if [ -n "$PREFERENCES" ]; then

            echo "$PREFERENCES" | sudo tee "/etc/apt/preferences.d/$repo.pref" >/dev/null || die

        fi

        APT_CACHE_DIRTY=1

        for i in "${!APT_REPO_REGISTRY[@]}"; do

            if [ "$repo" = "${APT_REPO_REGISTRY[$i]}" ]; then

                unset "APT_REPO_REGISTRY[$i]"
                unset "APT_REPO_KEY_URLS[$i]"
                unset "APT_REPO_ENTRIES[$i]"
                unset "APT_REPO_PACKAGES[$i]"
                unset "APT_REPO_PREFERENCES[$i]"

            fi

        done

        for i in "${!APT_REPO_QUEUE[@]}"; do

            if [ "$repo" = "${APT_REPO_QUEUE[$i]}" ]; then

                unset "APT_REPO_QUEUE[$i]"

            fi

        done

    done

}

# Usage: apt_install_deb "http://url.to/package.deb" [queue only (Y/n)]
function apt_install_deb() {

    command_exists wget || apt_force_install_packages "wget"

    # queue by default
    if [ "${2:-Y}" = "Y" ]; then

        APT_DEB_QUEUE+=("$1")

    else

        do_apt_install_deb "$1"

    fi

}

function do_apt_install_deb() {

    local PATHS DEB_PATHS=() SKIPPED=() NOT_SKIPPED=() DEB_PACKAGE DEB_VERSION INSTALLED_VERSION path

    mkdir -p "$APT_DEB_PATH" && pushd "$APT_DEB_PATH" >/dev/null || die "Error: unable to access $APT_DEB_PATH"

    console_message "Downloading $# deb $(single_or_plural "$#" package packages)..." "" "$CYAN"

    # allow "429 Too Many Requests"
    # shellcheck disable=SC2034
    DOWNLOAD_URLS_SKIP_REGEX='^\s*HTTP/[0-9.]+\s+429\b'

    PATHS="$(
        set -euo pipefail
        download_urls "$@"
    )" || die

    while IFS= read -r path; do

        DEB_PATHS+=("$path")

    done < <(echo "$PATHS")

    popd >/dev/null

    for path in "${!DEB_PATHS[@]}"; do

        DEB_PACKAGE="$(
            set -euo pipefail

            # shellcheck disable=SC2016
            dpkg-deb --showformat '${Package}' -W "${DEB_PATHS[$path]}" | tail -n 1
        )"

        if apt_package_installed "$DEB_PACKAGE"; then

            DEB_VERSION="$(
                set -euo pipefail

                # shellcheck disable=SC2016
                dpkg-deb --showformat '${Version}' -W "${DEB_PATHS[$path]}" | tail -n 1
            )"
            INSTALLED_VERSION="$(dpkg-query -f '${Version}' -W "$DEB_PACKAGE")"

            if dpkg --compare-versions "$DEB_VERSION" le "$INSTALLED_VERSION"; then

                SKIPPED+=("$DEB_PACKAGE")
                APT_INSTALLED+=("$DEB_PACKAGE")
                unset "DEB_PATHS[$path]"
                continue

            fi

        fi

        NOT_SKIPPED+=("$DEB_PACKAGE")

    done

    [ "${#NOT_SKIPPED[@]}" -gt "0" ] && console_message "Installing deb $(single_or_plural "${#NOT_SKIPPED[@]}" package packages):" "${NOT_SKIPPED[*]}" "$GREEN"

    if [ "${#DEB_PATHS[@]}" -gt "0" ]; then

        if sudo dpkg -EGi "${DEB_PATHS[@]}" || sudo aptitude -yf install; then

            APT_INSTALLED+=("${NOT_SKIPPED[@]}")
            APT_JUST_INSTALLED+=("${NOT_SKIPPED[@]}")
            APT_SKIPPED+=("${SKIPPED[@]}")
            apt_refresh_packages

        else

            die

        fi

    fi

}

# Usage: apt_remove_packages "package1 package2 ..."
function apt_remove_packages() {

    local p

    # shellcheck disable=SC2048
    for p in $*; do

        if apt_package_installed "$p" && ! array_search "$p" APT_REMOVE_QUEUE >/dev/null; then

            APT_REMOVE_QUEUE+=("$p")

        fi

    done

}

function apt_process_queue() {

    local q QUEUE INSTALL_QUEUE SILENT_QUEUE PRETTY_QUEUE SUDO_EXTRA=()

    if [ "${#APT_INSTALL_QUEUE[@]}" -gt "0" ]; then

        QUEUE=($(printf '%s\n' "${APT_PPA_QUEUE[@]}" "${APT_REPO_QUEUE[@]}" | sort | uniq))

        [ "${#QUEUE[@]}" -gt "0" ] && console_message "Adding ${#QUEUE[@]} $(single_or_plural ${#QUEUE[@]} repository repositories):" "${QUEUE[*]}" "$GREEN"

        for q in PPA REPO; do

            eval QUEUE='("${APT_'$q'_QUEUE[@]}")'

            [ "${#QUEUE[@]}" -gt "0" ] && {
                QUEUE=($(printf '%s\n' "${QUEUE[@]}" | sort | uniq))
                eval "apt_add_$(lower $q)" "${QUEUE[@]}" || die
            }

        done

        apt_make_cache_clean
        INSTALL_QUEUE=($(apt_get_package_list "${APT_INSTALL_QUEUE[*]}" "${APT_IGNORED[*]}" "${APT_SUPPRESSED[*]}" "${APT_REMOVE_QUEUE[*]}" "${APT_SILENCED[*]}" N))
        SILENT_QUEUE=($(apt_get_package_list "${APT_INSTALL_QUEUE[*]}" "${APT_IGNORED[*]}" "${APT_SUPPRESSED[*]}" "" "${APT_SILENCED[*]}" Y))
        PRETTY_QUEUE=($(apt_pretty_packages "$(apt_filter_packages "${INSTALL_QUEUE[*]} ${SILENT_QUEUE[*]}")" Y "$GREEN"))
        console_message "Applying ${#PRETTY_QUEUE[@]} package $(single_or_plural ${#PRETTY_QUEUE[@]} change changes):" "${PRETTY_QUEUE[*]}" "$GREEN"

        for q in INSTALL SILENT; do

            eval QUEUE='("${'$q'_QUEUE[@]}")'

            if [ "${#QUEUE[@]}" -gt "0" ]; then

                sudo "${SUDO_EXTRA[@]}" apt-get "${APT_GET_OPTIONS[@]}" install "${QUEUE[@]}" && {
                    APT_INSTALLED+=($(apt_filter_packages "${QUEUE[*]}" N))
                    APT_JUST_INSTALLED+=($(apt_filter_packages "${QUEUE[*]}" N))
                } || die

            fi

            SUDO_EXTRA+=("DEBIAN_FRONTEND=noninteractive")

        done

        APT_INSTALL_QUEUE=()
        APT_REMOVE_QUEUE=()
        apt_refresh_packages

    fi

    if [ "${#APT_DEB_QUEUE[@]}" -gt "0" ]; then

        do_apt_install_deb "${APT_DEB_QUEUE[@]}" && {
            APT_DEB_QUEUE=()
            apt_refresh_packages
        }

    fi

}

function apt_force_install_packages() {

    apt_install_packages "prerequisites" "$1" N N

}

function apt_upgrade_all() {

    apt_make_cache_clean

    console_message "Installing all available package updates..." "" "$GREEN"

    sudo apt-get "${APT_GET_OPTIONS[@]}" dist-upgrade && APT_CACHE_DIRTY=1 || die

}

# returns all changed configuration files (note: deleted files aren't detected)
function apt_get_changed_configuration_files() {

    command_exists debsums || apt_force_install_packages "debsums"

    sudo debsums -ce 2>/dev/null || die

}

# returns all new files under /etc
function apt_get_new_configuration_files() {

    command_exists debsums || apt_force_install_packages "debsums"

    sudo find /etc -type f | grep -vFf <(
        set -euo pipefail
        sudo debsums -e 2>/dev/null | sed -E 's/[[:space:]]*[A-Z]+$//' || die
    ) || die

}

APT_CACHE_DIRTY=1
APT_GUI_PACKAGES_AUTO=0
APT_DEB_PATH="$CACHE_DIR/deb"
APT_GET_OPTIONS=(-o "Acquire::ForceIPv4=true" -y)
APT_PPA_REGISTRY=()
APT_PPA_PACKAGES=()
APT_PPA_PREFERENCES=()
APT_REPO_REGISTRY=()
APT_REPO_KEY_URLS=()
APT_REPO_ENTRIES=()
APT_REPO_PACKAGES=()
APT_REPO_PREFERENCES=()
APT_INSTALLED=()
APT_JUST_INSTALLED=()
APT_IGNORED=()
APT_SUPPRESSED=()
APT_SILENCED=()
APT_INSTALL_QUEUE=()
APT_REMOVE_QUEUE=()
APT_PPA_QUEUE=()
APT_REPO_QUEUE=()
APT_DEB_QUEUE=()
APT_SKIPPED=()
