#!/bin/bash

function check_developer_tools() {

    local ATTEMPTS=0

    assert_command_exists xcode-select

    while ! xcode-select -p >/dev/null; do

        [ "$ATTEMPTS" -eq "0" ] || console_message "Command line developer tools aren't installed ($ATTEMPTS $(single_or_plural "$ATTEMPTS" attempt attempts) so far)" "" "$BOLD" "$RED"

        console_message "Requesting installation of the command line developer tools" "" "$CYAN"
        sudo xcode-select --install

        lk_pause "Press return when command line developer tools installation has completed"

        ((++ATTEMPTS))

    done

    # opendiff doesn't work if Xcode isn't active
    if [ -d "/Applications/Xcode.app" ]; then

        sudo xcode-select -switch "/Applications/Xcode.app" || die

    fi

}
